// client-react-old/src/components/common/Footer.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { 
  ShoppingBag, 
  Truck, 
  ShieldCheck, 
  RotateCcw, 
  CreditCard, 
  Mail, 
  Phone, 
  Clock, 
  Heart,
  ChevronRight
} from 'lucide-react';

export default function Footer() {
  return (
    <footer className="bg-slate-900 text-gray-300 border-t border-slate-800">
      {/* Value Proposition Highlights */}
      <div className="border-b border-slate-800/80 bg-slate-950/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div className="flex items-center space-x-3.5">
              <div className="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <Truck className="w-6 h-6" />
              </div>
              <div>
                <h4 className="text-white font-bold text-sm">Express Delivery</h4>
                <p className="text-xs text-gray-400">Under 2 hours or same day</p>
              </div>
            </div>

            <div className="flex items-center space-x-3.5">
              <div className="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div>
                <h4 className="text-white font-bold text-sm">100% Genuine</h4>
                <p className="text-xs text-gray-400">Direct from trusted brands</p>
              </div>
            </div>

            <div className="flex items-center space-x-3.5">
              <div className="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <RotateCcw className="w-6 h-6" />
              </div>
              <div>
                <h4 className="text-white font-bold text-sm">Easy Returns</h4>
                <p className="text-xs text-gray-400">Hassle-free doorstep pickup</p>
              </div>
            </div>

            <div className="flex items-center space-x-3.5">
              <div className="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <CreditCard className="w-6 h-6" />
              </div>
              <div>
                <h4 className="text-white font-bold text-sm">Safe &amp; Secure Pay</h4>
                <p className="text-xs text-gray-400">UPI, Cards &amp; Cash on Delivery</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Links */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-8">
          {/* Brand Info */}
          <div className="md:col-span-2 space-y-4">
            <Link to="/" className="flex items-center space-x-2.5">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-brand-700 to-brand-500 flex items-center justify-center text-white">
                <ShoppingBag className="w-5 h-5" />
              </div>
              <div>
                <div className="flex items-center space-x-1">
                  <span className="text-xl font-black text-white tracking-tight">TEZ</span>
                  <span className="text-xl font-black text-accent-500 tracking-tight">THAILA</span>
                </div>
              </div>
            </Link>
            <p className="text-xs text-gray-400 leading-relaxed max-w-sm">
              Tez Thaila is India's fast, fresh, and reliable e-commerce shopping destination. 
              From daily grocery staples, farm produce, and dairy to consumer electronics, 
              we bring authentic products right to your doorstep.
            </p>
            <div className="flex items-center space-x-3 text-xs text-gray-400">
              <span className="flex items-center"><Phone className="w-3.5 h-3.5 mr-1.5 text-brand-400" /> 1800-TEZ-THAILA</span>
              <span>•</span>
              <span className="flex items-center"><Mail className="w-3.5 h-3.5 mr-1.5 text-brand-400" /> support@tezthaila.com</span>
            </div>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="text-white font-bold text-xs uppercase tracking-wider mb-4">Categories</h4>
            <ul className="space-y-2 text-xs">
              <li><Link to="/products?category=groceries-staples" className="hover:text-white transition-colors">Groceries &amp; Staples</Link></li>
              <li><Link to="/products?category=dairy-breakfast" className="hover:text-white transition-colors">Dairy &amp; Breakfast</Link></li>
              <li><Link to="/products?category=fresh-fruits-vegetables" className="hover:text-white transition-colors">Fruits &amp; Vegetables</Link></li>
              <li><Link to="/products?category=snacks-beverages" className="hover:text-white transition-colors">Snacks &amp; Beverages</Link></li>
              <li><Link to="/products?category=electronics-audio" className="hover:text-white transition-colors">Electronics &amp; Audio</Link></li>
            </ul>
          </div>

          {/* Customer Service */}
          <div>
            <h4 className="text-white font-bold text-xs uppercase tracking-wider mb-4">Customer Care</h4>
            <ul className="space-y-2 text-xs">
              <li><Link to="/orders" className="hover:text-white transition-colors">Track Your Order</Link></li>
              <li><Link to="/account" className="hover:text-white transition-colors">Your Account</Link></li>
              <li><Link to="/cart" className="hover:text-white transition-colors">Shopping Cart</Link></li>
              <li><Link to="/wishlist" className="hover:text-white transition-colors">Your Wishlist</Link></li>
              <li><span className="hover:text-white cursor-pointer transition-colors">Return Policy</span></li>
            </ul>
          </div>

          {/* Newsletter */}
          <div>
            <h4 className="text-white font-bold text-xs uppercase tracking-wider mb-4">Get Special Offers</h4>
            <p className="text-xs text-gray-400 mb-3">
              Subscribe for exclusive flash deals, discounts, and festive coupons!
            </p>
            <div className="space-y-2">
              <input
                type="email"
                placeholder="Enter your email address"
                className="w-full px-3 py-2 bg-slate-800 text-white text-xs rounded-lg border border-slate-700 focus:outline-none focus:border-brand-500"
              />
              <button className="w-full py-2 bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs rounded-lg transition-colors">
                Subscribe
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Legal */}
      <div className="border-t border-slate-800 py-6 text-center text-xs text-gray-500">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-2">
          <p>© 2026 Tez Thaila India Private Limited. All rights reserved.</p>
          <div className="flex items-center space-x-4">
            <span className="text-[11px] font-semibold text-gray-400">Accepted Payments: UPI • RuPay • Visa • Mastercard • COD</span>
          </div>
        </div>
      </div>
    </footer>
  );
}

// client/src/app/components/common/footer.component.ts
import { Component, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LanguageService } from '../../services/language.service';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <footer class="bg-slate-900 dark:bg-slate-950 text-gray-300 border-t border-slate-800 transition-colors duration-200">
      <!-- Value Proposition Highlights -->
      <div class="border-b border-slate-800/80 bg-slate-950/40">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div class="flex items-center space-x-3.5">
              <div class="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <i class="pi pi-truck text-2xl"></i>
              </div>
              <div>
                <h4 class="text-white font-bold text-sm">{{ lang.t('expressDelivery') }}</h4>
                <p class="text-xs text-gray-400">{{ lang.t('expressDeliverySub') }}</p>
              </div>
            </div>

            <div class="flex items-center space-x-3.5">
              <div class="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <i class="pi pi-shield text-2xl"></i>
              </div>
              <div>
                <h4 class="text-white font-bold text-sm">{{ lang.t('genuinePromise') }}</h4>
                <p class="text-xs text-gray-400">{{ lang.t('genuinePromiseSub') }}</p>
              </div>
            </div>

            <div class="flex items-center space-x-3.5">
              <div class="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <i class="pi pi-sync text-2xl"></i>
              </div>
              <div>
                <h4 class="text-white font-bold text-sm">{{ lang.t('easyReturns') }}</h4>
                <p class="text-xs text-gray-400">{{ lang.t('easyReturnsSub') }}</p>
              </div>
            </div>

            <div class="flex items-center space-x-3.5">
              <div class="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400 flex-shrink-0">
                <i class="pi pi-wallet text-2xl"></i>
              </div>
              <div>
                <h4 class="text-white font-bold text-sm">{{ lang.t('codPay') }}</h4>
                <p class="text-xs text-gray-400">{{ lang.t('codPaySub') }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Main Links / Collapsible Sections -->
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-12">
        <div class="grid grid-cols-1 md:grid-cols-12 gap-8">
          <!-- Brand Info (Always open) -->
          <div class="md:col-span-4 space-y-4">
            <a routerLink="/" class="flex items-center space-x-2.5">
              <div class="w-9 h-9 rounded-xl bg-gradient-to-tr from-brand-700 to-brand-500 flex items-center justify-center text-white">
                <i class="pi pi-shopping-bag text-lg"></i>
              </div>
              <div class="flex items-center space-x-1">
                <span class="text-xl font-black text-white tracking-tight">TEZ</span>
                <span class="text-xl font-black text-accent-500 tracking-tight">THAILA</span>
              </div>
            </a>
            <p class="text-xs text-gray-400 leading-relaxed max-w-sm">
              {{ lang.t('footerAbout') }}
            </p>
            <div class="flex flex-col sm:flex-row sm:items-center gap-2 text-xs text-gray-400 pt-1">
              <span class="flex items-center"><i class="pi pi-phone mr-1.5 text-brand-400"></i> 1800-TEZ-THAILA</span>
              <span class="hidden sm:inline">•</span>
              <span class="flex items-center"><i class="pi pi-envelope mr-1.5 text-brand-400"></i> support&#64;tezthaila.com</span>
            </div>
          </div>

          <!-- Collapsible Column 1: Categories -->
          <div class="md:col-span-2 border-b md:border-b-0 border-slate-800 pb-4 md:pb-0">
            <button
              (click)="toggleSection('categories')"
              class="w-full flex items-center justify-between md:cursor-default text-left py-1 cursor-pointer"
            >
              <h4 class="text-white font-bold text-xs uppercase tracking-wider">{{ lang.t('categories') }}</h4>
              <i class="pi md:hidden text-xs text-gray-400 transition-transform duration-200"
                [ngClass]="openSections()['categories'] ? 'pi-chevron-up' : 'pi-chevron-down'"></i>
            </button>
            <div [ngClass]="openSections()['categories'] ? 'block' : 'hidden md:block'" class="pt-3">
              <ul class="space-y-2 text-xs">
                <li><a routerLink="/products" [queryParams]="{ category: 'groceries-staples' }" class="hover:text-white transition-colors">{{ lang.getCategoryName('groceries-staples', 'Groceries & Staples') }}</a></li>
                <li><a routerLink="/products" [queryParams]="{ category: 'dairy-breakfast' }" class="hover:text-white transition-colors">{{ lang.getCategoryName('dairy-breakfast', 'Dairy & Breakfast') }}</a></li>
                <li><a routerLink="/products" [queryParams]="{ category: 'fresh-fruits-vegetables' }" class="hover:text-white transition-colors">{{ lang.getCategoryName('fresh-fruits-vegetables', 'Fruits & Vegetables') }}</a></li>
                <li><a routerLink="/products" [queryParams]="{ category: 'snacks-beverages' }" class="hover:text-white transition-colors">{{ lang.getCategoryName('snacks-beverages', 'Snacks & Beverages') }}</a></li>
                <li><a routerLink="/products" [queryParams]="{ category: 'electronics-audio' }" class="hover:text-white transition-colors">{{ lang.getCategoryName('electronics-audio', 'Electronics & Audio') }}</a></li>
              </ul>
            </div>
          </div>

          <!-- Collapsible Column 2: Customer Care -->
          <div class="md:col-span-2 border-b md:border-b-0 border-slate-800 pb-4 md:pb-0">
            <button
              (click)="toggleSection('customerCare')"
              class="w-full flex items-center justify-between md:cursor-default text-left py-1 cursor-pointer"
            >
              <h4 class="text-white font-bold text-xs uppercase tracking-wider">{{ lang.t('customerCare') }}</h4>
              <i class="pi md:hidden text-xs text-gray-400 transition-transform duration-200"
                [ngClass]="openSections()['customerCare'] ? 'pi-chevron-up' : 'pi-chevron-down'"></i>
            </button>
            <div [ngClass]="openSections()['customerCare'] ? 'block' : 'hidden md:block'" class="pt-3">
              <ul class="space-y-2 text-xs">
                <li><a routerLink="/orders" class="hover:text-white transition-colors">{{ lang.t('trackOrder') }}</a></li>
                <li><a routerLink="/account" class="hover:text-white transition-colors">{{ lang.t('myProfile') }}</a></li>
                <li><a routerLink="/cart" class="hover:text-white transition-colors">{{ lang.t('cart') }}</a></li>
                <li><a routerLink="/wishlist" class="hover:text-white transition-colors">{{ lang.t('wishlist') }}</a></li>
                <li><a routerLink="/checkout" class="hover:text-white transition-colors">{{ lang.t('codPay') }}</a></li>
              </ul>
            </div>
          </div>

          <!-- Collapsible Column 3: Physical Store Locations -->
          <div class="md:col-span-4 border-b md:border-b-0 border-slate-800 pb-4 md:pb-0">
            <button
              (click)="toggleSection('locations')"
              class="w-full flex items-center justify-between md:cursor-default text-left py-1 cursor-pointer"
            >
              <div class="flex items-center space-x-2">
                <i class="pi pi-map-marker text-accent-400"></i>
                <h4 class="text-white font-bold text-xs uppercase tracking-wider">{{ lang.t('storeLocations') }}</h4>
              </div>
              <i class="pi md:hidden text-xs text-gray-400 transition-transform duration-200"
                [ngClass]="openSections()['locations'] ? 'pi-chevron-up' : 'pi-chevron-down'"></i>
            </button>
            <div [ngClass]="openSections()['locations'] ? 'block' : 'hidden md:block'" class="pt-3 space-y-2.5">
              <div class="p-3 rounded-xl bg-slate-800/80 dark:bg-slate-900/90 border border-slate-700/80 text-xs space-y-2">
                <div class="flex items-center justify-between text-white font-bold">
                  <div class="flex items-center space-x-1.5">
                    <span class="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                    <span class="text-emerald-300">{{ lang.t('patnaHubName') }}</span>
                  </div>
                  <span class="text-[10px] text-emerald-400 font-bold bg-emerald-950/80 border border-emerald-800/60 px-2 py-0.5 rounded-full">{{ lang.t('open') }}</span>
                </div>
                
                <p class="text-gray-300 text-[11px] leading-relaxed">
                  <i class="pi pi-building mr-1.5 text-accent-400"></i>
                  {{ lang.t('patnaHubAddress') }}
                </p>

                <div class="flex items-center text-[10px] text-gray-400 space-x-3">
                  <span><i class="pi pi-clock mr-1 text-accent-400"></i>{{ lang.t('timing') }}</span>
                  <span><i class="pi pi-phone mr-1 text-accent-400"></i>+91 612 2554400</span>
                </div>

                <div class="pt-2 border-t border-slate-700/60 flex items-center justify-between text-[11px]">
                  <span class="text-gray-400 font-mono text-[10px] flex items-center">
                    <i class="pi pi-compass mr-1 text-emerald-400"></i>
                    25.6154° N, 85.1240° E
                  </span>
                  <a
                    href="https://www.google.com/maps/search/?api=1&query=25.6154,85.1240"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="inline-flex items-center space-x-1 text-accent-400 hover:text-accent-300 font-bold text-[11px] transition-colors"
                  >
                    <span>{{ lang.t('viewOnMap') }}</span>
                    <i class="pi pi-external-link text-[10px]"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Bottom Legal -->
      <div class="border-t border-slate-800 py-6 text-center text-xs text-gray-500">
        <div class="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p>{{ lang.t('copyright') }}</p>
          <div class="flex items-center space-x-2">
            <span class="text-[11px] font-semibold text-gray-400 bg-slate-800/80 px-3 py-1 rounded-full border border-slate-700/80">
              {{ lang.t('codOnlyBadge') }}
            </span>
          </div>
        </div>
      </div>
    </footer>
  `
})
export class FooterComponent {
  lang = inject(LanguageService);

  openSections = signal<{ [key: string]: boolean }>({
    categories: false,
    customerCare: false,
    locations: true
  });

  toggleSection(key: string): void {
    this.openSections.update(state => ({
      ...state,
      [key]: !state[key]
    }));
  }
}
